# deploy mvc web app to azure using github actions

name: Deploy Squadup MVC

on:
    workflow_dispatch:

env:
    AZURE_WEBAPP_NAME: squadup-app        

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # checkout the repo
            - uses: actions/checkout@master
           
            # Setup .NET Core SDK
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: 7.0.x

             # Run dotnet build and publish
            - name: install dependencies
              run:
                dotnet restore
            - name: build project
              run:
                dotnet build --configuration Release
            
            # publish project
            - name: publish
              run:
                dotnet publish -c Release --no-build --output ./publish

            # deploy project
            - name: deploy
              uses: azure/webapps-deploy@v2
              with: 
                app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
                publish-profile: ${{ secrets.SQUADUP_SECRET  }} # Define secret variable in repository settings as per action documentation
                package: ./publish

