# deploy mvc web app to azure using github actions

name: Deploy Squadup MVC

on:
    workflow_dispatch:


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # checkout the repo
            - uses: actions/checkout@master
           
            # Setup .NET Core SDK
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: 7.0.x

             # Run dotnet build and publish
            - name: install dependencies
              run:
                dotnet restore
            - name: build project
              run:
                dotnet build --configuration Release
